language: python

python:
  #- "3.5"
  - "3.8"

install:
  - sudo apt-get update
  - sudo update-java-alternatives -s java-8-oracle
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION rdflib requests parameterized jupyter nose2 -c conda-forge
  - conda activate test-environment
  - pip install -r ci_test/requirements.txt
  - git clone https://github.com/edamontology/edamverify.git
  - cd edamverify
  - wget http://www.hermit-reasoner.com/download/current/HermiT.zip && unzip -o -d . HermiT.zip HermiT.jar

script:
  - cd edamverify
  - nose2 --with-coverage --verbose

notifications:
  email:
    - alban.gaignard@univ-nantes.fr
    - herve.menager@pasteur.fr
