name: ROBOT reasoner 

on:
  [push, pull_request, workflow_dispatch, workflow_call]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Set up 
      run: |
        git clone git@github.com:edamontology/edam-validation.git

    - name: run reason
      run: |
        cd edam-validation/robot/ 
        export PATH=/home/runner/work/edamontology/edamontology/edam-validation/robot:$PATH
        java -jar robot.jar reason --reasoner ELK   --input ../../EDAM_dev.owl -v 

